# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CloudFormationCreateOrUpdateStack@1
      inputs:
        awsCredentials: 'Aws ambryhill test'
        regionName: 'us-east-1'
        stackName: 'stack-ah-prod'
        templateSource: 's3'
        s3BucketName: 'ambryhill-cf'
        s3ObjectKey: 'prod-2020-05-27.json'
    
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag) 