# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: S3Download@1
      inputs:
        awsCredentials: 'Aws ambryhill test'
        regionName: 'us-east-1'
        bucketName: 'ambryhill-cf'
        sourceFolder: '/'
        globExpressions: 'prod-2020-05-27.json'
        targetFolder: '/'
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag) 