trigger:
- master

resources:
- repo: self

variables:
  envAH: 'prod'
  buildId: '$(Build.BuildId)'
  stackPrefix: 'stack-ah-prod-'
  # S3 for CloudFormation template
  s3Bucket: 'ambryhill-cf'
  s3BucketObjKey: 'prod-2020-05-31.json'
  # CloudFormation params
  cfRegionName: 'us-east-1'
  cfInstanceCount: '2'
  cfSubnets: 'subnet-09956b30369a7c713, subnet-0cf3a8c9703dc2ca3'
  cfVpcId: 'vpc-02777bc8e193269b2'
  cfKeyName: 'key_ambryhill_prod'
  cfInstanceType: 't2.micro'
  # docker build
  dockerBase: 'ah-base'
  dockerArgs: '--build-arg APP_DOMAIN=PRODUCTION'
  # ECR for repository
  ecrRepositoryName: 'prod-ambryhill-app'
  # Orchestrator ECS
  ecsTask: 'ah_prod'
  # Docker containers
  ecs1Name: 'app'
  ecs1Image: '207155759131.dkr.ecr.us-east-1.amazonaws.com/prod-ambryhill-app:$(buildId)'
  ecs1Cpu: '256'
  ecs1Memory: '256'
  # Orchestrator ECS service and cluster
  ecsCluster: 'ah_prod'
  ecsService: 'nodec'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CloudFormationCreateOrUpdateStack@1
      inputs:
        awsCredentials: 'Aws ambryhill test'
        regionName: 'us-east-1'
        stackName: 'stack-ah-prod-$(buildId)'
        templateSource: 's3'
        s3BucketName: 'ambryhill-cf'
        s3ObjectKey: 'prod-2020-05-31.json'
        templateParametersSource: 'inline'
        templateParameters: |
          -
            ParameterKey: 'AZs'
            ParameterValue: 'us-east-1d, us-east-1a'
          -
            ParameterKey: 'InstanceCount'
            ParameterValue: '2'
          -
            ParameterKey: 'Subnets'
            ParameterValue: 'subnet-09956b30369a7c713, subnet-0cf3a8c9703dc2ca3'
          -
            ParameterKey: 'VpcId'
            ParameterValue: 'vpc-02777bc8e193269b2'
          -
            ParameterKey: 'KeyName'
            ParameterValue: 'key_ambryhill_prod'
          -
            ParameterKey: 'InstanceType'
            ParameterValue: 't2.micro'
    - task: Docker@2
      inputs:
        repository: 'ah-base'
        command: 'build'
        Dockerfile: 'Dockerfile'
        arguments: '--build-arg APP_DOMAIN=PRODUCTION'
    - task: ECRPushImage@1
      inputs:
        awsCredentials: 'Aws ambryhill test'
        regionName: 'us-east-1'
        imageSource: 'imageid'
        sourceImageId: 'ah-base:$(buildId)'
        repositoryName: 'prod-ambryhill-app'
        pushTag: '$(buildId)'

    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'Aws ambryhill test'
        regionName: 'us-east-1'
        arguments: ''
        scriptType: 'inline'
        inlineScript: |
          aws ecs register-task-definition --family ah_prod --container-definitions "
              [
                 {
                    \"name\":\"app\",
                    \"image\":\"207155759131.dkr.ecr.us-east-1.amazonaws.com/prod-ambryhill-app:$(buildId)\",
                    \"cpu\":256,
                    \"memory\":256,
                    \"essential\":true,
                    \"portMappings\":[
                       {
                          \"containerPort\":80,
                          \"hostPort\":80
                       },
                       {
                          \"containerPort\":443,
                          \"hostPort\":443
                       }
                    ],
                    \"environment\":[
                       {
                        \"name\": \"conf\",
                        \"value\": \"prod\"
                        },
                       {
                          \"name\":\"env\",
                          \"value\":\"prod\"
                       }
                    ]
                 }
              ]" > revision.txt
          cat revision.txt | grep revision | awk '{print $2}' | sed 's/,/ /g' > Prod-$(buildId).txt
          TASK_DEFINITION=`cat Prod-$(buildId).txt`
          echo $TASK_DEFINITION
          aws ecs update-service --cluster ah_prod --service nodec --task-definition ah_prod:`cat Prod-$(buildId).txt`
        failOnStandardError: true
